feat: add pr lint rule

diff --git a/workflow/prLint.yml b/workflow/prLint.yml
--- a/workflow/prLint.yml
+++ b/workflow/prLint.yml
@@ -2,8 +2,33 @@ name: Pull Request Check Workflow
 on: 
   pull_request:
     types: [opened, edited, reopened, synchronize]
+
 jobs:
-  validate:
+  content_validate:
+    name: Valiate if PR is a valid cdk project
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Validate
+        run: |
+          echo "Validating if PR is a valid cdk project"
+          if [ -f "package.json" ]; then
+            echo "package.json file found"
+            if [ -f "cdk.json" ]; then
+              echo "cdk.json file found"
+              echo "Valid cdk project"
+            else
+              echo "cdk.json file not found"
+              echo "Invalid cdk project"
+              exit 1
+            fi
+          else
+            echo "package.json file not found"
+            echo "Invalid cdk project"
+            exit 1
+          fi
+  sematic_validate:
     name: Validate PR title
     runs-on: ubuntu-latest
     permissions:
@@ -12,12 +37,19 @@ jobs:
       - uses: amannn/action-semantic-pull-request@v5.0.2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          types: |-
+        with :
+          types: |
             feat
             fix
+            docs
+            style
+            refactor
+            perf
+            test
+            build
+            ci
             chore
-          requireScope: false
+            revert
   cfn_nag:
     name: cfn_nag
     runs-on: ubuntu-latest
@@ -25,13 +57,14 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
       - name: cfn_nag
+        working-directory: ./sample
         run: |
-          wget -q
-          unzip -q cfn_nag.zip -d ../cfn_nag
-          rm -r ./cfn_nag.zip
+          # install Ruby
+          sudo apt-get install ruby-full
+          gem install cfn-nag
           echo "CloudFormation template scanning utility installation complete `date`"
           echo "Starting CloudFormation template scanning `date` in `pwd`"
-          ../cfn_nag/bin/cfn_nag_scan --input-path .
+          cfn_nag_scan --input-path .
           echo "Completed CloudFormation template scanning `date`"
   viperlight:
     name: viperlight
