Update prLint.yml

diff --git a/.github/workflows/prLint.yml b/.github/workflows/prLint.yml
--- a/.github/workflows/prLint.yml
+++ b/.github/workflows/prLint.yml
@@ -2,8 +2,86 @@ name: Pull Request Check Workflow
 on: 
   pull_request:
     types: [opened, edited, reopened, synchronize]
-  workflow_dispatch:    
+
 jobs:
+  content_validate:
+    name: Valiate if PR is a valid cdk project
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Validate
+        run: |
+          echo "Validating if PR is a valid cdk project"
+          if [ -f "package.json" ]; then
+            echo "package.json file found"
+            if [ -f "cdk.json" ]; then
+              echo "cdk.json file found"
+              echo "Valid cdk project"
+            else
+              echo "cdk.json file not found"
+              echo "Invalid cdk project"
+              exit 1
+            fi
+          else
+            echo "package.json file not found"
+            echo "Invalid cdk project"
+            exit 1
+          fi
+  sematic_validate:
+    name: Validate PR title
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+    steps:
+      - uses: amannn/action-semantic-pull-request@v5.0.2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with :
+          types: |
+            feat
+            fix
+            docs
+            style
+            refactor
+            perf
+            test
+            build
+            ci
+            chore
+            revert
+  cfn_nag:
+    name: cfn_nag
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: cfn_nag
+        working-directory: ./sample
+        run: |
+          # install Ruby
+          sudo apt-get install ruby-full
+          gem install cfn-nag
+          echo "CloudFormation template scanning utility installation complete `date`"
+          echo "Starting CloudFormation template scanning `date` in `pwd`"
+          cfn_nag_scan --input-path .
+          echo "Completed CloudFormation template scanning `date`"
+  viperlight:
+    name: viperlight
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Viperlight
+        run: |
+          wget -q https://viperlight-scanner.s3.amazonaws.com/latest/.viperlightrc
+          wget -q https://viperlight-scanner.s3.amazonaws.com/latest/viperlight.zip
+          unzip -q viperlight.zip -d ../viperlight
+          rm -r ./viperlight.zip
+          echo "Content scanning utility installation complete `date`"
+          echo "Starting content scanning `date` in `pwd`"
+          ../viperlight/bin/viperlight scan -m files-contents -m files-aws -m files-binary -m files-entropy -m files-secrets
+          echo "Completed content scanning `date`"
   git-secrets:
     name: git-secrets
     runs-on: ubuntu-18.04
